name: build-and-test
on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.0.x' ]
    name: Dotnet ${{ matrix.dotnet }} build
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Clean
        run: dotnet clean -c Debug

      - name: Build
        run: dotnet build -c Debug

      - name: Test
        run: dotnet test -c Debug --no-build -l trx --verbosity=normal
          
      - name: Run Stryker
        run: |
          dotnet tool install dotnet-stryker
          dotnet stryker
          
      - name: Publish HTML results as artifacts
        uses: actions/upload-artifact@v1
        with:
          name: MutationResults
          path: ./tests/ForeverFactory.Tests/StrykerOutput